### ISSUE TITLE
Error with Sample Code

### ISSUE THREAD

**Issue by abdullah2993** [NebulousLabs/go-upnp#7]
The code compiles fine but when I run the exe it get stuck at `Discover()` and then throws this error.
```
(0x7c4aa0,0xc04200c1d0)panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x465b89]

goroutine 1 [running]:
panic(0x6576e0, 0xc04200c090)
        C:/Go/src/runtime/panic.go:500 +0x1af
github.com/NebulousLabs/go-upnp.(*IGD).ExternalIP(0x0, 0xc04200c1d0, 0xc04200c1d0, 0xc04207bf18, 0x4042e2)
        C:/Users/Abdullah Saleem/Documents/GO/src/github.com/NebulousLabs/go-upnp/upnp.go:54 +0x29
main.main()
        C:/Users/Abdullah Saleem/Documents/GO/Anonymizer/src/main.go:15 +0x6a
```

**Comment by lukechampine** [comment]
This is because the sample code omits error handling. `upnp.Discover` fails, so `d` is nil.
Try this instead:
```go
func main() {
    // connect to router
    d, err := upnp.Discover()
    if err != nil {
        fmt.Println(err)
        return
    }

    // discover external IP
    ip, err := d.ExternalIP()
    if err != nil {
        fmt.Println(err)
        return
    }
    fmt.Println("Your external IP is:", ip)

    // forward a port
    err = d.Forward(9001, "upnp test")
    if err != nil {
        fmt.Println(err)
        return
    }

    // un-forward a port
    err = d.Clear(9001)
    if err != nil {
        fmt.Println(err)
        return
    }

    // record router's location
    loc := d.Location()

    // connect to router directly
    d, err = upnp.Load(loc)
    if err != nil {
        fmt.Println(err)
        return
    }
}
```

**Comment by abdullah2993** [comment]
@lukechampine thanks. I was missing the return statements

**Comment by tlightsky** [comment]
helped me,
confirm my router doesn't support upnp :(

**Comment by abdullah2993** [comment]
@tlightsky you might need to enable it...?

**Comment by tlightsky** [comment]
I have tried.
It's a new UI of tplink, no upnp option.
I might have to flash an openwrt on it then.

**Comment by abdullah2993** [comment]
@tlightsky thats highly unlikely

**Comment by tlightsky** [comment]
btw, this example should be put to README.md @lukechampine

**Comment by lukechampine** [comment]
I agree @tlightsky, done.
